name: Clans
main: de.tobiyas.clans.Clans
version: 0.1
website: http://
author: tobiyas

description: >
             Clan Plugin for Bukkit
commands:
  clan:
    description:
    aliases: []
    usage:  |
            /clan
  gchat:
    description: guild chat
    aliases: [g]
    usage:  |
            /gchat <message>
  clancreate:
    description: creates a new clan
    aliases: []
    usage:  |
            /clancreate <clanname>
  acceptinvite:
    description: accepts an Invite to a clan.
    aliases: []
    usage:  |
            /acceptinvite
  declineinvite:
    description: declines an Invite
    aliases: []
    usage:  |
            /declineinvite